name: esm-2023
channels:
- conda-forge
dependencies:
- python>=3.11
- pip

  # main packages
- numpy
- scipy
- pandas>=2
- geopandas>=0.13.2
- xarray
- networkx
- yaml
- pyomo
- netcdf4
- pypsa>=0.25.1
- atlite>=0.2.11
- powerplantmatching>=0.5.7
- rasterio>=1.3.2
- pysheds

  # interactive python
- ipython
- jupyterlab

  # reading excel tables
- tabula-py
- xlrd
- lxml
- pytables
- pyxlsb
- openpyxl

  # geodata utilities
# - fiona
- shapely>2
# - proj
#- geopy
- pyepsg
- cartopy>=0.22
#- descartes
- country_converter

  # plotting
- matplotlib>=3.6
- plotly
- hvplot
- holoviews
- geoviews>=1.10
- graphviz

  # solvers
# - coincbc
# - glpk

  # publishing
- jupyter-book
- ghp-import

- pip:
  - highspy
